name: Test Minikube Runner

on:
  workflow_dispatch:

jobs:
  test-arc-runner:
    runs-on: pd-minikube-arc-runner
    steps:
      - name: Run a test command
        run: |
          echo "Hello from ARC self-hosted runner on Minikube!"
          hostname
          uname -a
